# Etapa de build
FROM maven:3.9.3-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa de runtime
FROM eclipse-temurin:17.0.12-jre-alpine
WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

# Configurações de memória críticas
ENV JAVA_OPTS="-Xms128m -Xmx256m -XX:MaxRAM=384m"
ENV SPRING_PROFILES_ACTIVE=prod

CMD ["sh", "-c", "java ${JAVA_OPTS} -jar app.jar --server.port=${PORT}"]