version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: springboot-app
    volumes:
      - .:/workspace:cached
    depends_on:
      - mysql
    command: sleep infinity
    ports:
      - "8080:8080"

volumes:
  mysql_data:
