server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha

info:
  app:
    name: Ecommerce API
    version: 1.0
    description: Documentação da API do sistema de Ecommerce.
  contact:
    name: Norwal Gomes
    email: norwalgomess@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

openapi:
  servers:
    - url: http://localhost:8080
      description: Dev Server
    - url: https://calm-nature-production.up.railway.app
      description: Prod Server
